version: "3"
services:
  binancetobq:
    build: .
    environment:
      GC_PROJECT_ID: ${GC_PROJECT_ID}
      BINANCETOBQ_DATASET: ${BINANCETOBQ_DATASET}
      BINANCETOBQ_INTERVALS: ${BINANCETOBQ_INTERVALS}
      BINANCETOBQ_SYMBOLS: ${BINANCETOBQ_SYMBOLS}
      BINANCETOBQ_MARKET_TYPE: ${BINANCETOBQ_MARKET_TYPE}
      BINANCETOBQ_LOG_LEVEL: ${BINANCETOBQ_LOG_LEVEL}
      YAPPI_ENABLED: ${YAPPI_ENABLED}
      GOOGLE_APPLICATION_CREDENTIALS: /google_credentials.json
    volumes:
      - ./src:/app/src:ro
      - ./tmp:/app/tmp
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./LICENSE}:/google_credentials.json:ro
